dependencies {
    // MetaWorld Mixins - SubWorldClient API
    implementation("com.github.Gordon-Frohman:MetaWorlds-Mixins:1.6.1b:dev") { transitive = false }

    // UniMixins - same version as ReCreate
    implementation("io.github.legacymoddingmc:unimixins:0.2.1:dev")

    // JOML - Matrix math
    implementation("org.joml:joml:1.10.8")

    // Development Annotations
    compileOnly("org.jetbrains:annotations:24.0.1")
}
