modName = Ponder 1.7.10
modId = ponder1710
modGroup = net.createmod.ponder1710
autoUpdateBuildScript = false
minecraftVersion = 1.7.10
forgeVersion = 10.13.4.1614
channel = stable
mappingsVersion = 12
remoteMappings = https://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/
developmentEnvironmentUserName = Developer
enableModernJavaSyntax = true
enableGenericInjection = false
generateGradleTokenClass = net.createmod.ponder1710.Tags
gradleTokenVersion = VERSION
replaceGradleTokenInFile =
apiPackage =
accessTransformersFile =
usesMixins = true
usesMixinDebug = false
mixinPlugin =
mixinsPackage = net.createmod.ponder1710.mixin
coreModClass =
containsMixinsAndOrCoreModOnly = false
forceEnableMixins = true
usesShadowedDependencies = true
minimizeShadowedDependencies = false
relocateShadowedDependencies = false
includeWellKnownRepositories = true
usesMavenPublishing = false
modrinthProjectId =
modrinthRelations =
curseForgeProjectId =
curseForgeRelations =
disableCheckstyle = true
disableSpotless = true
